---
- name: Interface validation
  hosts: all

  tasks:
    - name: L3 interface check
      ios_command:
        commands: sho ip int br | ex unassigned|0/3|Interf      
      register: l3_interfaces

    - name: Trunk interfaces
      ios_command:
        commands: sh interfaces trunk | be prune
      register: trunk_interfaces
      when: "'switches' in group_names"

    - name: Print swithces output
      debug:
        msg: 
        - "{{ l3_interfaces.stdout_lines }}"
        - "{{ trunk_interfaces.stdout_lines }}"
      when: "'switches' in group_names"

    - name: Print routers output
      debug:
        msg:
        - "{{ l3_interfaces.stdout_lines }}"
      when: "'routers' in group_names"

...
