---
- name: gather and print IOS/NXOS facts
  hosts: all
  tasks:
    - name: gather IOS facts
      ios_facts:
        gather_subset: all
      register: ios_facts
      when: ansible_network_os == 'ios'

    - name: show IOS facts
      debug:
        var: ios_facts

    

...
