---
- name: show l3 interface info
  hosts: campus
  
  tasks:
   - name: Gather some facts
     ios_facts:
     when: ansible_network_os == 'ios'
     register: output

   - name: show interfaces
     debug:
       msg: "{{ item }}"
     with_dict: "{{ output.ansible_facts.ansible_net_interfaces }}"
     when: item.value.operstatus == "up"

...
